baseURL = "http://dominio.com/"
languageCode = "es-es"
defaultContentLanguage = "es"
enableRobotsTXT = true
enableGitInfo = true
title = "Kodetica"
theme = "kode"

[menu]
  [[menu.main]]
    name = "Inicio"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Cursos"
    pre = "folder"
    url = "/cursos"
    weight = 2
  [[menu.main]]
    name = "Blog"
    pre = "pen"
    url = "/blog"
    weight = 3
  [[menu.main]]
    name = "Contacto"
    pre = "mail"
    url = "/contacto"
    weight = 4

[taxonomies]
  tag = "tags"
  category = "categorias"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[permalinks]
posts = "/blog/:year/:title/"
